# This file is auto-generated by GoReleaser on each release.
# It is kept here as a reference only; the canonical copy lives in
# https://github.com/eimarfandino/homebrew-tap/blob/main/Formula/mkcr.rb
class Mkcr < Formula
  desc "Create and list ServiceNow Standard Change requests without touching the UI"
  homepage "https://github.com/eimarfandino/snow-cr-cli"
  url "https://github.com/eimarfandino/snow-cr-cli/releases/download/v0.1.0/mkcr_darwin_arm64.tar.gz"
  sha256 "<sha256-placeholder-filled-by-goreleaser>"
  version "0.1.0"

  def install
    bin.install "mkcr"
  end

  test do
    system "#{bin}/mkcr", "--help"
  end
end
